# Generated by Django 5.0.6 on 2024-06-11 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Məhsulun adı')),
                ('endusedate', models.DateField(verbose_name='Son istifadə tarixi')),
                ('orderduration', models.DurationField(verbose_name='Çatdırılma müddəti')),
                ('originalprice', models.IntegerField(max_length=20, verbose_name='Məhsulun dəyəri')),
                ('sellingprice', models.IntegerField(max_length=30, verbose_name='Məhsulun satış qiyməti')),
                ('slug', models.SlugField(unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
