# Generated by Django 5.0.6 on 2024-06-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='originalprice',
            field=models.IntegerField(verbose_name='Məhsulun dəyəri'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sellingprice',
            field=models.IntegerField(verbose_name='Məhsulun satış qiyməti'),
        ),
    ]
